import { useState, type KeyboardEvent } from 'react';
import { toolkit } from '../data';
import { GENERIC_ICONS, IconArrowUpRight } from './icons';
const notes=['The foundations I use to turn ideas into reliable programs.','Tools for understanding images, motion and language.','Models, frameworks and patterns for systems that reason and act.','APIs, applications and the data that connects them.','Infrastructure for deploying and operating software.','The everyday tools that support the development process.'];
export function Toolkit(){
 const [active,setActive]=useState(0);const cat=toolkit[active];
 const keyNav=(e:KeyboardEvent<HTMLButtonElement>,i:number)=>{let next=i;if(e.key==='ArrowDown'||e.key==='ArrowRight')next=(i+1)%toolkit.length;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')next=(i+toolkit.length-1)%toolkit.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=toolkit.length-1;else return;e.preventDefault();setActive(next);document.getElementById('tool-tab-'+next)?.focus();};
 return <section id="toolkit" className="toolkit section-padding"><div className="toolkit-heading"><p className="eyebrow">05 / TECHNICAL TOOLKIT</p><h2>The right tools.<br/><span>For the right problem.</span></h2><p>Explore the technologies behind my work, from the first experiment to the application around it.</p></div>
 <div className="toolkit-browser"><div className="toolkit-nav" role="tablist" aria-label="Technology categories">{toolkit.map((c,i)=><button id={'tool-tab-'+i} role="tab" aria-selected={i===active} aria-controls="tool-panel" tabIndex={i===active?0:-1} key={c.name} onClick={()=>setActive(i)} onKeyDown={e=>keyNav(e,i)}><span>0{i+1}</span><b>{c.name}</b><span aria-hidden="true"><IconArrowUpRight/></span></button>)}</div>
 <div id="tool-panel" className="toolkit-panel" role="tabpanel" aria-labelledby={'tool-tab-'+active} tabIndex={0}><div className="toolkit-panel-heading"><span className="toolkit-panel-index" aria-hidden="true">0{active+1}</span><div><h3>{cat.name}</h3><p>{notes[active]}</p></div></div><div className="toolkit-items" key={active}>{cat.items.map((item,i)=>{const Generic=item.generic?GENERIC_ICONS[item.generic]:null;return <div className="toolkit-item" style={{animationDelay:i*35+'ms'}} key={item.name}>{item.logo?<img src={'/assets/logos/'+item.logo+'.svg'} alt="" width="28" height="28"/>:Generic?<Generic/>:null}<span>{item.name}</span></div>;})}</div><p className="toolkit-panel-foot">TECHNOLOGIES &amp; PRACTICES / {cat.items.length} ITEMS</p></div></div></section>;
}
